# Generated by Django 3.2.7 on 2021-09-25 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import pos.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("option_1", models.CharField(max_length=100)),
                ("option_2", models.CharField(max_length=100)),
                ("option_3", models.CharField(max_length=100)),
                ("option_4", models.CharField(max_length=100)),
                (
                    "date_at",
                    models.DateField(validators=[pos.validators.validate_date]),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "option",
                    models.CharField(
                        choices=[
                            ("OPTION_1", "Option 1"),
                            ("OPTION_2", "Option 2"),
                            ("OPTION_3", "Option 3"),
                            ("OPTION_4", "Option 4"),
                        ],
                        max_length=100,
                    ),
                ),
                ("preference", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pos.menu"
                    ),
                ),
                (
                    "user",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
