name: Build

on: pull_request

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            ### Redis
            BROKER_URL: ${{ secrets.BROKER_URL }}
            ### Database
            SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build
              run: make
            # - name: Run Black
            #  run: make lint
            - name: Run Tests
              run: make test
